/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sql_aula8_telas;
import java.sql.*;
import sql_aula7_conexao.Conexao;
import javax.swing.*;
import sql_aula7_telas.Cliente;

/**
 *
 * @author 42121742018.1
 */
public class Aparelho extends javax.swing.JFrame {

    /**
     * Creates new form Aparelho
     */
    protected int idAparelho;
    private String nomeAparelho;
    private double preco;
    private int idCliente;
    
    Connection conexao=null;
    PreparedStatement linguagem=null;
    ResultSet linha=null;
    
    public Aparelho(){
        initComponents();
        conexao=Conexao.conexao();
    }
    
    void limpacampo(){
        jcodigo.setText("");
        jnome.setText("");
        jpreco.setText("");
        jcliente.setSelectedItem("Selecione");
        jnome.requestFocus();
    }
    
    void novo(){
        jcodigo.setEnabled(true);
        jnome.setEnabled(true);
        jpreco.setEnabled(true);
        jcliente.setEnabled(true);
        jsalvar.setEnabled(true);
        jnome.requestFocus();
    }
    
    void cliente(){
        String sql="select nomeCliente from cliente";
        try{
            linguagem=conexao.prepareStatement(sql);
            linha=linguagem.executeQuery();
            while(linha.next()){
                jcliente.addItem(linha.getString("nomeCliente"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    void codigo(){
        String sql="select idCliente from cliente where nomeCliente='"+jcliente.getSelectedItem()+"'";
        try{
            linguagem=conexao.prepareStatement(sql);
            linha=linguagem.executeQuery();
            while(linha.next()){
                jcodcliente.setText(linha.getString("idCliente"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcodcliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcodigo = new javax.swing.JTextField();
        jnome = new javax.swing.JTextField();
        jpreco = new javax.swing.JTextField();
        jcliente = new javax.swing.JComboBox<>();
        jbcliente = new javax.swing.JButton();
        jnovo = new javax.swing.JButton();
        jsalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 290));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jcodcliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jcodcliente);
        jcodcliente.setBounds(150, 200, 40, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Código do aparelho");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Preço");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 120, 120, 30);

        jcodigo.setEnabled(false);
        jcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcodigoActionPerformed(evt);
            }
        });
        getContentPane().add(jcodigo);
        jcodigo.setBounds(150, 40, 150, 30);

        jnome.setEnabled(false);
        jnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomeActionPerformed(evt);
            }
        });
        getContentPane().add(jnome);
        jnome.setBounds(150, 80, 150, 30);

        jpreco.setEnabled(false);
        jpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprecoActionPerformed(evt);
            }
        });
        getContentPane().add(jpreco);
        jpreco.setBounds(150, 120, 150, 30);

        jcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jcliente.setEnabled(false);
        jcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclienteActionPerformed(evt);
            }
        });
        getContentPane().add(jcliente);
        jcliente.setBounds(150, 160, 150, 30);

        jbcliente.setText("Cliente");
        jbcliente.setMaximumSize(new java.awt.Dimension(79, 23));
        jbcliente.setMinimumSize(new java.awt.Dimension(79, 23));
        jbcliente.setPreferredSize(new java.awt.Dimension(79, 23));
        jbcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbclienteActionPerformed(evt);
            }
        });
        getContentPane().add(jbcliente);
        jbcliente.setBounds(300, 220, 80, 23);

        jnovo.setText("Novo");
        jnovo.setMaximumSize(new java.awt.Dimension(63, 23));
        jnovo.setMinimumSize(new java.awt.Dimension(63, 23));
        jnovo.setPreferredSize(new java.awt.Dimension(63, 23));
        jnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnovoActionPerformed(evt);
            }
        });
        getContentPane().add(jnovo);
        jnovo.setBounds(310, 40, 70, 23);

        jsalvar.setText("Salvar");
        jsalvar.setEnabled(false);
        jsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jsalvar);
        jsalvar.setBounds(310, 80, 70, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Chave primária");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 200, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Cliente");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 160, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcodigoActionPerformed

    private void jnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnomeActionPerformed

    private void jprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jprecoActionPerformed

    private void jclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclienteActionPerformed
        // TODO add your handling code here:
        codigo();
    }//GEN-LAST:event_jclienteActionPerformed

    private void jnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnovoActionPerformed
        // TODO add your handling code here:
        novo();
    }//GEN-LAST:event_jnovoActionPerformed

    private void jsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsalvarActionPerformed

    private void jbclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbclienteActionPerformed
        // TODO add your handling code here:
        new Cliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbclienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cliente();//botao direito no jframe depois eventos>window>windowopened
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aparelho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbcliente;
    private javax.swing.JComboBox<String> jcliente;
    private javax.swing.JLabel jcodcliente;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JTextField jnome;
    private javax.swing.JButton jnovo;
    private javax.swing.JTextField jpreco;
    private javax.swing.JButton jsalvar;
    // End of variables declaration//GEN-END:variables
}
