/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula14exercicios;

import javax.swing.JOptionPane;

/**
 *
 * @author 42121742018.1
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldTurno = new javax.swing.JTextField();
        fieldNome = new javax.swing.JTextField();
        fieldMatrícula = new javax.swing.JTextField();
        fieldTurma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        enviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(330, 230));
        setPreferredSize(null);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 69, 22);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Turno: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 60, 20);

        fieldTurno.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        getContentPane().add(fieldTurno);
        fieldTurno.setBounds(130, 110, 100, 20);

        fieldNome.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(fieldNome);
        fieldNome.setBounds(130, 50, 100, 20);

        fieldMatrícula.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        getContentPane().add(fieldMatrícula);
        fieldMatrícula.setBounds(130, 70, 100, 20);

        fieldTurma.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        getContentPane().add(fieldTurma);
        fieldTurma.setBounds(130, 90, 100, 20);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nome: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 50, 60, 20);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Matrícula: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 70, 60, 20);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Turma: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 90, 60, 20);

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(60, 150, 61, 23);

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar);
        enviar.setBounds(190, 150, 63, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        ModeloEstudante model=new ModeloEstudante();
        Notas NOT=new Notas();
        if((fieldMatrícula.getText().equals("")) && (fieldNome.getText().equals("")) && (fieldTurma.getText().equals("")) && (fieldTurno.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Preencher todos os campos");
        }
        else{
            model.setMatrícula(fieldMatrícula.getText());
            model.setNome(fieldNome.getText());
            model.setTurma(fieldTurma.getText());
            model.setTurno(fieldTurno.getText());
            NOT.exportarDados(model);
            NOT.setVisible(true);
        }
    }//GEN-LAST:event_enviarActionPerformed

    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviar;
    private javax.swing.JTextField fieldMatrícula;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldTurma;
    private javax.swing.JTextField fieldTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
