/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula14exercicios;

/**
 *
 * @author 42121742018.1
 */
public class MédiaSituação extends javax.swing.JFrame {

    /**
     * Creates new form MédiaSituação
     */
    public MédiaSituação() {
        initComponents();
    }
    
    public void exportarDados2(ModeloNotas model2){
        label1Nota.setText(model2.getPrimeiraNota());
        label2Nota.setText(model2.getSegundaNota());
        labelMédia.setText(model2.getMédia());
        labelSituação.setText(model2.getSituação());
    }
    //public void exportarDados3 (ModeloMédia model3){
        
        //labelMédia.setText(model3.getMédia());
        //labelSituação.setText(model3.getSituação());
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelSituação = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label1Nota = new javax.swing.JLabel();
        label2Nota = new javax.swing.JLabel();
        labelMédia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 260));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Média & situação");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 140, 30);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 180, 51, 23);

        jButton2.setText("Voltar");
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 180, 61, 23);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Situação: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 130, 90, 14);

        labelSituação.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(labelSituação);
        labelSituação.setBounds(200, 130, 90, 14);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Segunda nota: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 90, 90, 14);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Média: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 110, 90, 14);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Primeira nota: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 70, 90, 14);

        label1Nota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(label1Nota);
        label1Nota.setBounds(200, 70, 90, 14);

        label2Nota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(label2Nota);
        label2Nota.setBounds(200, 90, 90, 14);

        labelMédia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(labelMédia);
        labelMédia.setBounds(200, 110, 90, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MédiaSituação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MédiaSituação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MédiaSituação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MédiaSituação.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MédiaSituação().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label1Nota;
    private javax.swing.JLabel label2Nota;
    private javax.swing.JLabel labelMédia;
    private javax.swing.JLabel labelSituação;
    // End of variables declaration//GEN-END:variables
}
